package com.amazecc.app.shared.ui.strings

object Strings {
    val appName = "AmazeCC"

    val ok = "OK"
    val cancel = "Cancel"
    val save = "Save"
    val delete = "Delete"
    val retry = "Retry"
    val close = "Close"
    val yes = "Yes"
    val no = "No"
    val done = "Done"
    val submit = "Submit"
    val confirm = "Confirm"
    val back = "Back"
    val next = "Next"
    val skip = "Skip"
    val loading = "Loading..."
    val search = "Search"
    val refresh = "Refresh"
    val settings = "Settings"
    val logout = "Logout"
    val login = "Login"
    val signIn = "Sign In"
    val signUp = "Sign Up"
    val error = "Error"
    val success = "Success"
    val warning = "Warning"
    val info = "Info"

    val networkError = "Network error. Please check your connection."
    val somethingWentWrong = "Something went wrong. Please try again."
    val noData = "No data available"
    val noResults = "No results found"
    val pullToRefresh = "Pull to refresh"

    val emailOrRegNumber = "Email or Registration Number"
    val password = "Password"
    val forgotPassword = "Forgot Password?"
    val loginToContinue = "Login to continue"
    val loginSuccess = "Login successful!"
    val loginFailed = "Login failed. Please check your credentials."
    val loggingIn = "Logging in..."

    val home = "Home"
    val academics = "Academics"
    val events = "Events"
    val more = "More"

    val attendance = "Attendance"
    val timetable = "Timetable"
    val marks = "Marks"
    val grades = "Grades"
    val courses = "Courses"
    val curriculum = "Curriculum"
    val examSchedule = "Exam Schedule"
    val gpaPredictor = "GPA Predictor"
    val odTracker = "OD Tracker"
    val tasks = "Tasks"
    val calendar = "Calendar"
    val freeClassrooms = "Free Classrooms"
    val circulars = "Circulars"

    val hostel = "Hostel"
    val transport = "Transport"
    val cabShare = "Cab Share"
    val library = "Library"
    val moodle = "Moodle"
    val profile = "Profile"
    val documents = "Documents"
    val payments = "Payments"
    val clubs = "Clubs"
    val projects = "Projects"
    val wishlist = "Wishlist"

    val darkMode = "Dark Mode"
    val lightMode = "Light Mode"
    val systemDefault = "System Default"
    val notifications = "Notifications"
    val language = "Language"
    val about = "About"
    val help = "Help"
    val privacyPolicy = "Privacy Policy"
    val termsOfService = "Terms of Service"
    val version = "Version"
    val rateUs = "Rate Us"
    val shareApp = "Share App"
    val reportBug = "Report Bug"
    val contactUs = "Contact Us"

    val syncing = "Syncing..."
    val syncComplete = "Sync complete"
    val syncFailed = "Sync failed"
    val lastSync = "Last synced"
    val syncingData = "Syncing your data..."

    val deleteConfirmation = "Are you sure you want to delete this?"
    val logoutConfirmation = "Are you sure you want to log out?"
}
