# Gradle Properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.mpp.androidSourceSetLayoutVersion=2

# Dependency Versions
kotlin.native.ignoreDisabledTargets=true
kotlin.version=2.0.0
compose.version=1.6.10
agp.version=8.2.2
ktor.version=2.3.11
coroutines.version=1.8.1
serialization.version=1.6.3
androidx.activity.version=1.9.0
androidx.appcompat.version=1.6.1
