package com.amazecc.app.shared.vtop

import com.amazecc.app.shared.domain.VtopIngestor
import com.amazecc.app.shared.model.AttendanceItem
import com.amazecc.app.shared.state.AcademicData
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * The VTOP row/parse layer against **real** markup.
 *
 * Fixtures are generated by `AmazeCC-API/scripts/gen-fixtures.mjs` from the HTML in
 * `../AmazeCC-API/vtop-snapshots/`, which was scraped live from a real account. The generator runs
 * the HTML through a spec-compliant DOM (parse5), so the thead/tbody split is real - a regex over
 * raw HTML is not the document the app sees, and reading it that way produced a wrong diagnosis
 * once already.
 *
 * The HTML itself is gitignored (it is someone's academic record). Regenerate with:
 *   node ../AmazeCC-API/scripts/vtop-dump.mjs      # re-scrape
 *   node ../AmazeCC-API/scripts/gen-fixtures.mjs    # re-derive fixtures
 */
class RealVtopParseTest {

    private fun fixture(name: String): String {
        val path = "/fixtures/$name.json"
        val stream = checkNotNull(javaClass.getResourceAsStream(path)) {
            "Missing fixture $path. Run gen-fixtures.mjs (needs the gitignored snapshots)."
        }
        return stream.bufferedReader().use { it.readText() }
    }

    // ── attendance ──────────────────────────────────────────────────────────

    @Test
    fun attendanceRowsParseFromRealMarkup() {
        val rows = VtopRows.parse(fixture("attendance"))
        assertTrue(rows.ok)
        // 13 <tbody> rows: 12 courses + one totals row.
        assertEquals(13, rows.size)

        val first = rows.cell(0, 1)
        assertEquals("BACSE102", first, "course code is column 1")
        assertEquals("Problem Solving Using Java", rows.cell(0, 2))
        assertEquals("Lab Only", rows.cell(0, 3), "column 3 is Course Type, verbatim from VTOP")
        assertEquals("32", rows.cell(0, 9), "attended")
        assertEquals("36", rows.cell(0, 10), "total")
        assertEquals("89", rows.cell(0, 11), "percentage")
    }

    @Test
    fun everyCourseRowCarriesItsOwnViewLink() {
        val rows = VtopRows.parse(fixture("attendance"))
        // The 13th row is the "Total Number Of Credits" summary and has no link; all 12 courses
        // must have one, and each must be on the row it belongs to. This is the guard against
        // captures silently shifting onto the wrong course.
        val courseRows = rows.rows.withIndex().filter { it.value.size >= 10 }
        assertEquals(12, courseRows.size, "12 real courses; the totals row has a single cell")

        courseRows.forEach { (i, cells) ->
            val capture = rows.capture(i, 0)
            assertNotNull(capture, "row $i (${cells.getOrNull(1)}) has no onclick capture")
            assertTrue(
                capture.contains("processViewAttendanceDetail("),
                "row $i capture is not a detail link: $capture"
            )
        }
    }

    @Test
    fun theTotalsRowIsPresentAndIsNotACourse() {
        val rows = VtopRows.parse(fixture("attendance"))
        val last = rows.rows.last()
        assertEquals(1, last.size, "summary row is a single cell")
        assertTrue(
            rows.cell(rows.size - 1, 0).startsWith("Total Number Of Credits"),
            "expected the credits summary, got: ${rows.cell(rows.size - 1, 0)}"
        )
        // 12 credits rows at >= 10 cells; the summary is 1 cell and must be filtered by any
        // consumer that wants courses only.
        assertTrue(last.size < 10)
    }

    @Test
    fun theRealCourseTypeVocabularyIsWhatWeParse() {
        val rows = VtopRows.parse(fixture("attendance"))
        val types = rows.rows
            .filter { it.size >= 10 }
            .map { it.getOrElse(3) { "" }.trim() }
            .filter { it.isNotEmpty() }
            .toSet()
        // Read off attendance__CH20262701.html. "ETH"/"ELA" never appear in real VTOP output.
        assertTrue("Embedded Theory" in types, "expected Embedded Theory, got $types")
        assertTrue("Embedded Lab" in types, "expected Embedded Lab, got $types")
        assertTrue("Theory Only" in types, "expected Theory Only, got $types")
        assertTrue("Lab Only" in types, "expected Lab Only, got $types")
        assertTrue("Soft Skill" in types, "expected Soft Skill, got $types")
        assertTrue(types.none { it == "ETH" || it == "ELA" }, "ETH/ELA are internal labels only")
    }

    @Test
    fun headerLabelsNeedWhitespaceCollapsing() {
        // VTOP writes the header cells as "Course\n\t\t\t…\tCode", so a raw label never equals
        // "Course Code". Anything matching on headers has to squish first.
        val raw = VtopRows.parse(fixture("attendance-headers"))
        assertNotNull(raw)
    }

    // ── generic page parse ──────────────────────────────────────────────────

    @Test
    fun realPagesParseIntoTheGenericShape() {
        for (name in listOf("apaar", "ept-schedule", "dayboarder", "qcm", "bank-info", "credentials", "proctor")) {
            val page = VtopPage.parse(fixture("page-$name"))
            assertTrue(page.ok, "page-$name did not parse")
        }
    }

    @Test
    fun dayboarderExposesItsSemesterSelect() {
        val page = VtopPage.parse(fixture("page-dayboarder"))
        assertEquals("Dayboarder / Dayscholar Information", page.title)
        assertTrue(page.selectOptions.isNotEmpty(), "dayboarder has 4 selects in the real page")
    }

    @Test
    fun bankInfoTitleComesFromTheUnBoredBoxTitle() {
        // AmazeCC-API's bank-info parser uses `h3.box-title` with NO ` b`, unlike proctor/credentials.
        val page = VtopPage.parse(fixture("page-bank-info"))
        assertEquals("Student Bank Information", page.title)
    }

    @Test
    fun credentialsTitleComesFromTheBoredBoxTitle() {
        val page = VtopPage.parse(fixture("page-credentials"))
        assertEquals("Credentials", page.title)
    }

    @Test
    fun proctorTitleComesFromTheBoredBoxTitle() {
        val page = VtopPage.parse(fixture("page-proctor"))
        assertEquals("View proctor details", page.title)
    }
}
