package com.amazecc.app.shared.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import com.amazecc.app.shared.ffcs.CourseLock

import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.amazecc.app.shared.state.FfcsViewModel
import com.amazecc.app.shared.theme.AmazeTheme
import com.amazecc.app.shared.ui.components.*

@Composable
fun FfcsPlannerScreen() {
    val colors = AmazeTheme.colors
    
    val targetCourses by FfcsViewModel.targetCourses.collectAsState()
    val locks by FfcsViewModel.locks.collectAsState()
    val generated by FfcsViewModel.generatedTimetables.collectAsState()
    val error by FfcsViewModel.errorMsg.collectAsState()
    val isGenerating by FfcsViewModel.isGenerating.collectAsState()

    var activeTab by remember { mutableStateOf(0) }

    Column(modifier = Modifier.fillMaxSize().background(colors.background)) {
        ScreenHeader(
            title = "FFCS Planner",
            description = "Plan your timetable"
        )
        
        // Tabs
        Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp)) {
            val tabs = listOf("Target Courses", "Generated TTs")
            tabs.forEachIndexed { index, title ->
                val selected = activeTab == index
                Box(
                    modifier = Modifier
                        .weight(1f)
                        .padding(horizontal = 4.dp)
                        .clip(RoundedCornerShape(8.dp))
                        .background(if (selected) colors.accent else colors.surface)
                        .clickable { activeTab = index }
                        .padding(vertical = 8.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        title, 
                        style = AmazeTheme.typography.caption.copy(
                            fontWeight = FontWeight.Bold,
                            color = if (selected) colors.textPrimary else colors.textSecondary
                        )
                    )
                }
            }
        }
        
        Spacer(modifier = Modifier.height(8.dp))
        
        Column(modifier = Modifier.fillMaxSize().padding(horizontal = 16.dp)) {
            if (activeTab == 0) {
                // Target Courses & Manual Constraints
                if (targetCourses.isEmpty()) {
                    Box(modifier = Modifier.weight(1f), contentAlignment = Alignment.Center) {
                        Text("No target courses added yet.", color = colors.textMuted)
                    }
                } else {
                    LazyColumn(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(12.dp), contentPadding = PaddingValues(bottom = 88.dp)) {
                        items(locks) { lock ->
                            ConstraintCard(lock)
                        }
                    }
                }
                
                Spacer(modifier = Modifier.height(16.dp))
                
                AmazeButton(
                    text = "Auto Generate",
                    icon = Icons.Rounded.AutoAwesome,
                    variant = ButtonVariant.PRIMARY,
                    modifier = Modifier.fillMaxWidth().padding(bottom = 16.dp),
                    onClick = { 
                        activeTab = 1
                        FfcsViewModel.generate() 
                    }
                )
            } else {
                // Generated Timetables Output
                if (isGenerating) {
                    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                        CircularProgressIndicator(color = colors.accent)
                    }
                } else if (generated.isEmpty()) {
                    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                        Text(error ?: "No results found.", color = colors.danger)
                    }
                } else {
                    LazyColumn(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(16.dp), contentPadding = PaddingValues(bottom = 88.dp)) {
                        items(generated) { tt ->
                            AmazeCard(modifier = Modifier.fillMaxWidth()) {
                                Column {
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                                        Text(tt.name, style = AmazeTheme.typography.body.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary))
                                        
                                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                            Box(modifier = Modifier.clip(RoundedCornerShape(8.dp)).background(colors.accent.copy(alpha=0.15f)).padding(horizontal = 8.dp, vertical = 4.dp)) {
                                                Text("Half Days: ${tt.metrics.halfDays}", style = AmazeTheme.typography.smallLabel.copy(color = colors.accent, fontWeight = FontWeight.Bold))
                                            }
                                            Box(modifier = Modifier.clip(RoundedCornerShape(8.dp)).background(colors.danger.copy(alpha=0.15f)).padding(horizontal = 8.dp, vertical = 4.dp)) {
                                                Text("Gaps: ${tt.metrics.gaps}", style = AmazeTheme.typography.smallLabel.copy(color = colors.danger, fontWeight = FontWeight.Bold))
                                            }
                                        }
                                    }
                                    
                                    Spacer(modifier = Modifier.height(12.dp))
                                    HorizontalDivider(color = colors.border)
                                    Spacer(modifier = Modifier.height(12.dp))
                                    
                                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                        tt.courses.forEach { course ->
                                            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                                Text(course.code, style = AmazeTheme.typography.caption.copy(color = colors.textPrimary, fontWeight = FontWeight.Bold))
                                                Text(course.slots.joinToString("+"), style = AmazeTheme.typography.caption.copy(color = colors.accent))
                                            }
                                        }
                                    }
                                    
                                    Spacer(modifier = Modifier.height(16.dp))
                                    AmazeButton(
                                        text = "Select & Save",
                                        icon = Icons.Rounded.Check,
                                        variant = ButtonVariant.PRIMARY,
                                        modifier = Modifier.fillMaxWidth(),
                                        onClick = {
                                            val attendanceItems = tt.courses.map { c ->
                                                com.amazecc.app.shared.model.AttendanceItem(
                                                    slNo = "",
                                                    courseCode = c.code,
                                                    courseTitle = c.title,
                                                    courseType = c.type,
                                                    slotName = c.slots.joinToString("+"),
                                                    faculty = c.faculty,
                                                    registrationDate = "",
                                                    attendanceDate = "",
                                                    attendedClasses = 0,
                                                    totalClasses = 0,
                                                    attendancePercentage = "0"
                                                )
                                            }
                                            com.amazecc.app.shared.state.AppState.updateAttendance(
                                                com.amazecc.app.shared.model.AttendanceRes(
                                                    attendance = attendanceItems
                                                )
                                            )
                                            com.amazecc.app.shared.state.AppState.switchTopLevel(com.amazecc.app.shared.state.Screen.ATTENDANCE)
                                        }
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun ConstraintCard(lock: CourseLock) {
    val colors = AmazeTheme.colors
    var expanded by remember { mutableStateOf(false) }

    AmazeCard(modifier = Modifier.fillMaxWidth().clickable { expanded = !expanded }) {
        Column {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                Column(modifier = Modifier.weight(1f)) {
                    Text(lock.code, style = AmazeTheme.typography.smallLabel.copy(color = colors.textMuted))
                    Text(lock.title, style = AmazeTheme.typography.body.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary), maxLines = 1, overflow = TextOverflow.Ellipsis)
                }
                
                Row(verticalAlignment = Alignment.CenterVertically) {
                    if (lock.allowedFaculty.isNotEmpty() || lock.allowedSlots.isNotEmpty()) {
                        Icon(Icons.Rounded.Lock, contentDescription = null, tint = colors.danger, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Locked", style = AmazeTheme.typography.caption.copy(color = colors.danger, fontWeight = FontWeight.Bold))
                    } else {
                        Text("Any", style = AmazeTheme.typography.caption.copy(color = colors.success, fontWeight = FontWeight.Bold))
                    }
                }
            }
            
            if (expanded) {
                Spacer(modifier = Modifier.height(12.dp))
                HorizontalDivider(color = colors.border)
                Spacer(modifier = Modifier.height(12.dp))
                
                Text("Select preferred options (leave unselected for any):", style = AmazeTheme.typography.caption.copy(color = colors.textSecondary))
                Spacer(modifier = Modifier.height(8.dp))
                
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    lock.offerings.forEach { offer ->
                        val parts = offer.split("|") // Faculty|Slot|Room
                        val isLocked = lock.allowedFaculty.contains(parts[0]) && lock.allowedSlots.contains(parts[1])
                        
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .clip(RoundedCornerShape(8.dp))
                                .background(if (isLocked) colors.accent.copy(alpha=0.1f) else colors.surface)
                                .border(1.dp, if (isLocked) colors.accent else colors.border, RoundedCornerShape(8.dp))
                                .clickable {
                                    val newFaculties = if (isLocked) emptyList() else listOf(parts[0])
                                    val newSlots = if (isLocked) emptyList() else listOf(parts[1])
                                    FfcsViewModel.setLock(lock.code, newSlots, newFaculties)
                                }
                                .padding(12.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column {
                                Text(parts[0], style = AmazeTheme.typography.caption.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary))
                                Text(parts[1], style = AmazeTheme.typography.smallLabel.copy(color = colors.textSecondary))
                            }
                            if (isLocked) {
                                Icon(Icons.Rounded.Check, contentDescription = null, tint = colors.accent, modifier = Modifier.size(16.dp))
                            }
                        }
                    }
                }
            }
        }
    }
}
