package com.amazecc.app.shared.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.amazecc.app.shared.ffcs.*
import com.amazecc.app.shared.state.FfcsViewModel
import com.amazecc.app.shared.theme.AmazeTheme
import com.amazecc.app.shared.ui.components.*
import kotlinx.coroutines.launch

@Composable
fun FfcsPlannerScreen() {
    val colors = AmazeTheme.colors
    val scope = rememberCoroutineScope()
    val isLoading by FfcsViewModel.isLoading.collectAsState()
    val allCourses by FfcsViewModel.courseOfferings.collectAsState()
    val selectedCodes by FfcsViewModel.selectedCodes.collectAsState()
    val locks by FfcsViewModel.locks.collectAsState()
    val generated by FfcsViewModel.generatedTimetables.collectAsState()
    val error by FfcsViewModel.errorMsg.collectAsState()
    val isGenerating by FfcsViewModel.isGenerating.collectAsState()
    val blockedSlots by FfcsViewModel.blockedSlots.collectAsState()

    var activeTab by remember { mutableStateOf(0) }
    var showGeneratorModal by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        if (allCourses.isEmpty()) {
            FfcsViewModel.initFromCsv()
        }
    }

    Box(modifier = Modifier.fillMaxSize().background(colors.background)) {
        ScreenHeader(
            title = "FFCS Planner",
            description = "Select courses, generate timetables"
        )

        Column(modifier = Modifier.fillMaxSize().padding(horizontal = 16.dp)) {
            HeaderSpacer()

            Row(
                modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp),
                horizontalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                val tabs = listOf("Courses", "Timetable", "Results")
                tabs.forEachIndexed { index, title ->
                    val selected = activeTab == index
                    Box(
                        modifier = Modifier
                            .weight(1f)
                            .clip(RoundedCornerShape(8.dp))
                            .background(if (selected) colors.accent else colors.surface)
                            .clickable { activeTab = index }
                            .padding(vertical = 8.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(
                            title,
                            style = AmazeTheme.typography.caption.copy(
                                fontWeight = FontWeight.Bold,
                                color = if (selected) colors.textPrimary else colors.textSecondary
                            )
                        )
                    }
                }
            }

            if (isLoading) {
                Box(modifier = Modifier.weight(1f).fillMaxWidth(), contentAlignment = Alignment.Center) {
                    CircularProgressIndicator(color = colors.accent)
                }
                return@Column
            }

            Box(modifier = Modifier.weight(1f).fillMaxWidth()) {
                when (activeTab) {
                    0 -> CourseSelectionTab(
                        allCourses = allCourses,
                        selectedCodes = selectedCodes,
                        locks = locks,
                        blockedSlots = blockedSlots,
                        onToggleCourse = { FfcsViewModel.toggleCourse(it) },
                        onSelectOffering = { code, offering -> FfcsViewModel.selectOffering(code, offering) }
                    )
                    1 -> TimetableTab(
                        selectedCodes = selectedCodes,
                        allCourses = allCourses,
                        locks = locks,
                        blockedSlots = blockedSlots,
                        onToggleBlockSlot = { FfcsViewModel.toggleBlockSlot(it) },
                        onGenerate = { showGeneratorModal = true }
                    )
                    2 -> ResultsTab(
                        generated = generated,
                        isGenerating = isGenerating,
                        error = error,
                        onClear = { FfcsViewModel.clearResults() }
                    )
                }
            }
        }

        if (showGeneratorModal) {
            GeneratorModal(
                selectedCodes = selectedCodes,
                allCourses = allCourses,
                locks = locks,
                isGenerating = isGenerating,
                onDismiss = { showGeneratorModal = false },
                onGenerate = {
                    showGeneratorModal = false
                    FfcsViewModel.generate()
                    activeTab = 2
                }
            )
        }
    }
}

@Composable
private fun CourseSelectionTab(
    allCourses: List<Pair<String, List<CourseOffering>>>,
    selectedCodes: Set<String>,
    locks: List<CourseLock>,
    blockedSlots: Set<String>,
    onToggleCourse: (String) -> Unit,
    onSelectOffering: (String, CourseOffering) -> Unit
) {
    val colors = AmazeTheme.colors
    var search by remember { mutableStateOf("") }
    var expandedCourse by remember { mutableStateOf<String?>(null) }

    val filtered = remember(allCourses, search) {
        if (search.isBlank()) allCourses
        else allCourses.filter { (code, offerings) ->
            code.contains(search, ignoreCase = true) ||
            offerings.any { it.title.contains(search, ignoreCase = true) }
        }
    }

    Column(modifier = Modifier.fillMaxSize()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            OutlinedTextField(
                value = search,
                onValueChange = { search = it },
                modifier = Modifier.weight(1f),
                placeholder = {
                    Text("Search by code or title...",
                        style = AmazeTheme.typography.body.copy(fontSize = 13.sp, color = colors.textMuted))
                },
                leadingIcon = { Icon(Icons.Rounded.Search, null, tint = colors.textMuted) },
                singleLine = true,
                shape = RoundedCornerShape(12.dp),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = colors.accent.copy(alpha = 0.5f),
                    unfocusedBorderColor = colors.border,
                    focusedTextColor = colors.textPrimary,
                    unfocusedTextColor = colors.textPrimary,
                    cursorColor = colors.accent
                )
            )
            if (selectedCodes.isNotEmpty()) {
                IconButton(onClick = { FfcsViewModel.resetSelection() }) {
                    Icon(Icons.Rounded.Clear, null, tint = colors.danger)
                }
            }
        }

        Spacer(Modifier.height(4.dp))

        if (selectedCodes.isNotEmpty()) {
            Row(
                modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(8.dp))
                    .background(colors.accent.copy(alpha = 0.08f)).padding(horizontal = 12.dp, vertical = 6.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    "${selectedCodes.size} selected",
                    style = AmazeTheme.typography.smallLabel.copy(color = colors.accent, fontWeight = FontWeight.Bold)
                )
                Text(
                    "Scroll to see all",
                    style = AmazeTheme.typography.smallLabel.copy(fontSize = 9.sp, color = colors.textMuted)
                )
            }
            Spacer(Modifier.height(4.dp))
        }

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            verticalArrangement = Arrangement.spacedBy(6.dp),
            contentPadding = PaddingValues(bottom = 96.dp)
        ) {
            items(filtered, key = { it.first }) { (code, offerings) ->
                val isSelected = selectedCodes.contains(code)
                val isExpanded = expandedCourse == code
                val lock = locks.find { it.code.equals(code, ignoreCase = true) }
                val hasLock = lock != null && (lock.allowedFaculty.isNotEmpty() || lock.allowedSlots.isNotEmpty())

                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(10.dp))
                        .background(if (isSelected) colors.accent.copy(alpha = 0.06f) else colors.surface)
                        .border(
                            1.dp,
                            if (hasLock) colors.warning else if (isSelected) colors.accent.copy(alpha = 0.3f) else colors.border,
                            RoundedCornerShape(10.dp)
                        )
                ) {
                    Row(
                        modifier = Modifier.fillMaxWidth().clickable { expandedCourse = if (isExpanded) null else code }.padding(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Checkbox(
                            checked = isSelected,
                            onCheckedChange = { onToggleCourse(code) },
                            colors = CheckboxDefaults.colors(
                                checkedColor = colors.accent,
                                uncheckedColor = colors.border
                            ),
                            modifier = Modifier.size(20.dp)
                        )
                        Spacer(Modifier.width(8.dp))
                        Column(modifier = Modifier.weight(1f)) {
                            Text(code, style = AmazeTheme.typography.smallLabel.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary, fontSize = 11.sp))
                            Text(
                                offerings.firstOrNull()?.title ?: "",
                                style = AmazeTheme.typography.caption.copy(color = colors.textSecondary, fontSize = 11.sp),
                                maxLines = 1, overflow = TextOverflow.Ellipsis
                            )
                        }
                        if (hasLock) {
                            Icon(Icons.Rounded.Lock, null, tint = colors.danger, modifier = Modifier.size(14.dp))
                            Spacer(Modifier.width(4.dp))
                        }
                        Text("${offerings.size}", style = AmazeTheme.typography.smallLabel.copy(fontSize = 9.sp, color = colors.textMuted))
                        Spacer(Modifier.width(2.dp))
                        Icon(if (isExpanded) Icons.Rounded.ExpandLess else Icons.Rounded.ExpandMore, null, tint = colors.textMuted, modifier = Modifier.size(18.dp))
                    }

                    if (isExpanded) {
                        offerings.forEach { offering ->
                            val isLocked = lock != null &&
                                lock.allowedSlots.contains(offering.slot) &&
                                lock.allowedFaculty.contains(offering.faculty)

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable { onSelectOffering(code, offering) }
                                    .padding(horizontal = 36.dp, vertical = 6.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Box(
                                    modifier = Modifier
                                        .size(18.dp)
                                        .clip(RoundedCornerShape(4.dp))
                                        .background(if (isLocked) colors.accent.copy(alpha = 0.15f) else Color.Transparent)
                                        .border(1.5.dp, if (isLocked) colors.accent else colors.border, RoundedCornerShape(4.dp)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    if (isLocked) {
                                        Icon(Icons.Rounded.Check, null, tint = colors.accent, modifier = Modifier.size(12.dp))
                                    }
                                }
                                Spacer(Modifier.width(8.dp))
                                Text(offering.faculty, style = AmazeTheme.typography.caption.copy(fontSize = 11.sp, fontWeight = FontWeight.Medium, color = colors.textPrimary),
                                    modifier = Modifier.weight(1f), maxLines = 1, overflow = TextOverflow.Ellipsis)
                                Text(offering.slot, style = AmazeTheme.typography.smallLabel.copy(fontSize = 10.sp, color = colors.accent, fontWeight = FontWeight.Bold),
                                    modifier = Modifier.width(60.dp))
                                Text(offering.room, style = AmazeTheme.typography.smallLabel.copy(fontSize = 9.sp, color = colors.textMuted),
                                    maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.width(60.dp))
                            }
                        }
                        Spacer(Modifier.height(4.dp))
                    }
                }
            }
        }
    }
}

@Composable
private fun TimetableTab(
    selectedCodes: Set<String>,
    allCourses: List<Pair<String, List<CourseOffering>>>,
    locks: List<CourseLock>,
    blockedSlots: Set<String>,
    onToggleBlockSlot: (String) -> Unit,
    onGenerate: () -> Unit
) {
    val colors = AmazeTheme.colors

    val currentCourses = remember(selectedCodes, allCourses, locks) {
        if (selectedCodes.isEmpty()) return@remember emptyList()

        allCourses.filter { (code, _) -> selectedCodes.contains(code) }.flatMap { (code, offerings) ->
            val lock = locks.find { it.code.equals(code, ignoreCase = true) }
            val hasLock = lock != null && (lock.allowedSlots.isNotEmpty() || lock.allowedFaculty.isNotEmpty())

            if (hasLock && lock != null) {
                offerings.filter { o ->
                    val slotMatch = lock.allowedSlots.isEmpty() || lock.allowedSlots.contains(o.slot)
                    val facMatch = lock.allowedFaculty.isEmpty() || lock.allowedFaculty.contains(o.faculty)
                    slotMatch && facMatch
                }.map { o ->
                    AddedCourse(
                        id = "${o.code}_${o.slot}_${o.faculty}",
                        code = o.code,
                        title = o.title,
                        slots = o.slot.split("+").map { it.trim() },
                        faculty = o.faculty,
                        venue = o.room,
                        credits = o.credits,
                        type = o.type,
                        color = FfcsConstants.COLORS[selectedCodes.toList().indexOf(o.code).coerceIn(0, FfcsConstants.COLORS.size - 1)]
                    )
                }
            } else {
                val first = offerings.firstOrNull() ?: return@flatMap emptyList()
                listOf(
                    AddedCourse(
                        id = "${first.code}_${first.slot}_${first.faculty}",
                        code = first.code,
                        title = first.title,
                        slots = first.slot.split("+").map { it.trim() },
                        faculty = first.faculty,
                        venue = first.room,
                        credits = first.credits,
                        type = first.type,
                        color = FfcsConstants.COLORS[selectedCodes.toList().indexOf(first.code).coerceIn(0, FfcsConstants.COLORS.size - 1)]
                    )
                )
            }
        }
    }

    Column(modifier = Modifier.fillMaxSize()) {
        if (selectedCodes.isEmpty()) {
            Box(modifier = Modifier.weight(1f).fillMaxWidth(), contentAlignment = Alignment.Center) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(Icons.Rounded.ViewTimeline, null, tint = colors.textMuted, modifier = Modifier.size(48.dp))
                    Spacer(Modifier.height(8.dp))
                    Text("Select courses in the Courses tab to see your timetable", color = colors.textSecondary, textAlign = TextAlign.Center)
                }
            }
        } else {
            FfcsTimetableGrid(
                courses = currentCourses,
                blockedSlots = blockedSlots,
                onToggleBlockSlot = onToggleBlockSlot,
                modifier = Modifier.weight(1f)
            )

            Spacer(Modifier.height(12.dp))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                AmazeButton(
                    text = "Generate Timetables (${selectedCodes.size} courses)",
                    icon = Icons.Rounded.AutoAwesome,
                    variant = ButtonVariant.PRIMARY,
                    modifier = Modifier.weight(1f),
                    onClick = onGenerate
                )
            }

            Spacer(Modifier.height(8.dp))

            Text(
                "Tap any cell to block that slot. Blocked slots are excluded from generation.",
                style = AmazeTheme.typography.smallLabel.copy(color = colors.textMuted, fontSize = 9.sp),
                textAlign = TextAlign.Center,
                modifier = Modifier.fillMaxWidth()
            )
        }
    }
}

@Composable
private fun ResultsTab(
    generated: List<TimetableState>,
    isGenerating: Boolean,
    error: String?,
    onClear: () -> Unit
) {
    val colors = AmazeTheme.colors
    var selectedTtIndex by remember { mutableStateOf(0) }
    var showSaveDialog by remember { mutableStateOf(false) }

    Column(modifier = Modifier.fillMaxSize()) {
        if (isGenerating) {
            Box(modifier = Modifier.weight(1f).fillMaxWidth(), contentAlignment = Alignment.Center) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    CircularProgressIndicator(color = colors.accent)
                    Spacer(Modifier.height(8.dp))
                    Text("Generating timetables...", color = colors.textSecondary, style = AmazeTheme.typography.body.copy(fontSize = 13.sp))
                }
            }
        } else if (generated.isEmpty()) {
            Box(modifier = Modifier.weight(1f).fillMaxWidth(), contentAlignment = Alignment.Center) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    if (error != null) {
                        Icon(Icons.Rounded.Warning, null, tint = colors.danger, modifier = Modifier.size(48.dp))
                        Spacer(Modifier.height(8.dp))
                        Text(error, color = colors.danger, textAlign = TextAlign.Center)
                    } else {
                        Icon(Icons.Rounded.AutoAwesome, null, tint = colors.textMuted, modifier = Modifier.size(48.dp))
                        Spacer(Modifier.height(8.dp))
                        Text("Go to Timetable tab and tap Generate", color = colors.textSecondary, textAlign = TextAlign.Center)
                    }
                }
            }
        } else {
            val currentTt = generated.getOrNull(selectedTtIndex)

            Column(modifier = Modifier.weight(1f)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("${generated.size} timetables found", style = AmazeTheme.typography.body.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary))
                    Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                        IconButton(onClick = { selectedTtIndex = (selectedTtIndex - 1).coerceAtLeast(0) }) {
                            Icon(Icons.Rounded.ChevronLeft, null, tint = if (selectedTtIndex > 0) colors.textPrimary else colors.textMuted)
                        }
                        Text("${selectedTtIndex + 1} / ${generated.size}", style = AmazeTheme.typography.caption.copy(color = colors.textSecondary))
                        IconButton(onClick = { selectedTtIndex = (selectedTtIndex + 1).coerceAtMost(generated.size - 1) }) {
                            Icon(Icons.Rounded.ChevronRight, null, tint = if (selectedTtIndex < generated.size - 1) colors.textPrimary else colors.textMuted)
                        }
                    }
                }

                Spacer(Modifier.height(8.dp))

                if (currentTt != null) {
                    MetricsRow(currentTt.metrics, colors)

                    Spacer(Modifier.height(8.dp))

                    FfcsTimetableGrid(
                        courses = currentTt.courses,
                        blockedSlots = emptySet(),
                        onToggleBlockSlot = {},
                        modifier = Modifier.weight(1f)
                    )

                    Spacer(Modifier.height(8.dp))

                    AmazeButton(
                        text = "Save This Timetable",
                        icon = Icons.Rounded.Save,
                        variant = ButtonVariant.PRIMARY,
                        modifier = Modifier.fillMaxWidth(),
                        onClick = {
                            val items = currentTt.courses.map { c ->
                                com.amazecc.app.shared.model.AttendanceItem(
                                    courseCode = c.code,
                                    courseTitle = c.title,
                                    courseType = c.type,
                                    slotName = c.slots.joinToString("+"),
                                    faculty = c.faculty
                                )
                            }
                            com.amazecc.app.shared.state.AppState.updateAttendance(
                                com.amazecc.app.shared.model.AttendanceRes(attendance = items)
                            )
                            showSaveDialog = true
                        }
                    )
                }
            }
        }
    }

    if (showSaveDialog) {
        AlertDialog(
            onDismissRequest = { showSaveDialog = false },
            title = { Text("Timetable Saved") },
            text = { Text("This timetable has been saved as your current attendance schedule.") },
            confirmButton = {
                TextButton(onClick = {
                    showSaveDialog = false
                    com.amazecc.app.shared.state.AppState.switchTopLevel(com.amazecc.app.shared.state.Screen.ATTENDANCE)
                }) { Text("View Attendance") }
            },
            dismissButton = {
                TextButton(onClick = { showSaveDialog = false }) { Text("Stay") }
            }
        )
    }
}

@Composable
private fun MetricsRow(metrics: TimetableMetrics, colors: com.amazecc.app.shared.theme.AmazeColors) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        MetricBadge("Free Half-Days", "${metrics.halfDays}", colors.accent, colors)
        MetricBadge("Gaps", "${metrics.gaps}h", colors.danger, colors)
        if (metrics.buildingDashes > 0) {
            MetricBadge("Dashes", "${metrics.buildingDashes}", colors.warning, colors)
        }
        if (metrics.socialScore > 0) {
            MetricBadge("Social", "${metrics.socialScore}%", colors.successText, colors)
        }
        if (metrics.isLongWeekend) {
            MetricBadge("Long Wknd", "Yes", Color(0xFF10B981), colors)
        }
    }
}

@Composable
private fun MetricBadge(label: String, value: String, color: Color, colors: com.amazecc.app.shared.theme.AmazeColors) {
    Column(
        modifier = Modifier.clip(RoundedCornerShape(8.dp)).background(color.copy(alpha = 0.1f)).padding(horizontal = 8.dp, vertical = 6.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(value, style = AmazeTheme.typography.caption.copy(fontWeight = FontWeight.Bold, color = color, fontSize = 14.sp))
        Text(label, style = AmazeTheme.typography.smallLabel.copy(color = colors.textSecondary, fontSize = 8.sp))
    }
}

@Composable
private fun GeneratorModal(
    selectedCodes: Set<String>,
    allCourses: List<Pair<String, List<CourseOffering>>>,
    locks: List<CourseLock>,
    isGenerating: Boolean,
    onDismiss: () -> Unit,
    onGenerate: () -> Unit
) {
    val colors = AmazeTheme.colors
    var uniqueFaculty by remember { mutableStateOf(false) }
    var morningPref by remember { mutableStateOf(false) }
    var maxResults by remember { mutableStateOf(50) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text("Auto Generator Settings", style = AmazeTheme.typography.body.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary))
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                Text(
                    "Generating for ${selectedCodes.size} course(s):",
                    style = AmazeTheme.typography.caption.copy(color = colors.textSecondary)
                )

                Row(
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    selectedCodes.forEach { code ->
                        val lock = locks.find { it.code.equals(code, ignoreCase = true) }
                        val hasLock = lock != null && (lock.allowedFaculty.isNotEmpty() || lock.allowedSlots.isNotEmpty())
                        Box(
                            modifier = Modifier.clip(RoundedCornerShape(6.dp))
                                .background(if (hasLock) colors.warning.copy(alpha = 0.15f) else colors.accent.copy(alpha = 0.1f))
                                .padding(horizontal = 8.dp, vertical = 4.dp)
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                if (hasLock) {
                                    Icon(Icons.Rounded.Lock, null, tint = colors.warning, modifier = Modifier.size(10.dp))
                                    Spacer(Modifier.width(2.dp))
                                }
                                Text(code, style = AmazeTheme.typography.smallLabel.copy(fontSize = 9.sp, color = if (hasLock) colors.warning else colors.accent))
                            }
                        }
                    }
                }

                HorizontalDivider(color = colors.border)

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Unique Faculty", style = AmazeTheme.typography.body.copy(color = colors.textPrimary, fontSize = 13.sp))
                    Switch(
                        checked = uniqueFaculty,
                        onCheckedChange = { uniqueFaculty = it },
                        colors = SwitchDefaults.colors(checkedThumbColor = colors.accent, checkedTrackColor = colors.accent.copy(alpha = 0.3f))
                    )
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Morning Only (before 2 PM)", style = AmazeTheme.typography.body.copy(color = colors.textPrimary, fontSize = 13.sp))
                    Switch(
                        checked = morningPref,
                        onCheckedChange = { morningPref = it },
                        colors = SwitchDefaults.colors(checkedThumbColor = colors.accent, checkedTrackColor = colors.accent.copy(alpha = 0.3f))
                    )
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Max Results", style = AmazeTheme.typography.body.copy(color = colors.textPrimary, fontSize = 13.sp))
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        IconButton(onClick = { maxResults = (maxResults - 10).coerceAtLeast(10) }) {
                            Icon(Icons.Rounded.Remove, null, tint = colors.textPrimary)
                        }
                        Text("$maxResults", style = AmazeTheme.typography.body.copy(fontWeight = FontWeight.Bold, color = colors.textPrimary))
                        IconButton(onClick = { maxResults = (maxResults + 10).coerceAtMost(500) }) {
                            Icon(Icons.Rounded.Add, null, tint = colors.textPrimary)
                        }
                    }
                }
            }
        },
        confirmButton = {
            AmazeButton(
                text = "Generate",
                icon = Icons.Rounded.AutoAwesome,
                variant = ButtonVariant.PRIMARY,
                onClick = {
                    FfcsViewModel.setUniqueFaculty(uniqueFaculty)
                    FfcsViewModel.setMorningPreference(morningPref)
                    FfcsViewModel.setMaxResults(maxResults)
                    onGenerate()
                }
            )
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Cancel", color = colors.textSecondary) }
        }
    )
}
