plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.jetbrains.compose)
    alias(libs.plugins.compose.compiler)
}

import java.util.Properties

val generateVersionInfo = tasks.register("generateVersionInfo") {
    val versionFile = rootProject.file("version.properties")
    val outputDir = layout.buildDirectory.dir("generated/versionInfo/kotlin")
    inputs.file(versionFile)
    outputs.dir(outputDir)
    doLast {
        val props = Properties().apply {
            versionFile.inputStream().use { load(it) }
        }
        val versionName = props.getProperty("VERSION_NAME") ?: error("VERSION_NAME missing in version.properties")
        val versionCode = props.getProperty("VERSION_CODE") ?: error("VERSION_CODE missing in version.properties")
        val packageDir = outputDir.get().asFile.resolve("com/amazecc/app/shared/utils")
        packageDir.mkdirs()
        packageDir.resolve("VersionInfo.kt").writeText(
            """
            |// Generated by generateVersionInfo - do not edit.
            |package com.amazecc.app.shared.utils
            |
            |object VersionInfo {
            |    const val VERSION_NAME: String = "$versionName"
            |    const val VERSION_CODE: Int = $versionCode
            |}
            |""".trimMargin()
        )
    }
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir(layout.buildDirectory.dir("generated/versionInfo/kotlin"))
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateVersionInfo)
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }
}

kotlin {
    targets.getByName("android")
    
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(libs.compose.ui.backhandler)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            
            // Ktor
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kamel.image)
            implementation(libs.multiplatform.settings)
            implementation(libs.multiplatform.settings.no.arg)
        }
        
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.activity.compose)
        }
        
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }

    android {
        namespace = "com.amazecc.app.shared"
        compileSdk = 35
        minSdk = 24
        androidResources {
            enable = true
        }
    }
}
